sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t gudqls97/docker-react-app -f Dockerfile.dev .

script: 
  - docker run -e CI=true gudqls97/docker-react-app

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-react-app2"
  env: "DockerReactApp2-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-415457253772"
  bucket_path: "docker-react-app2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY



